// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	ID        string `json:"id"`
	Winner    *User  `json:"winner"`
	Loser     *User  `json:"loser"`
	IsTie     bool   `json:"isTie"`
	Sport     *Sport `json:"sport"`
	CreatedAt string `json:"createdAt"`
}

type NewGame struct {
	SportName string           `json:"sportName"`
	Players   []*PlayerSummary `json:"players"`
}

type NewUser struct {
	Username  string  `json:"username"`
	Password  string  `json:"password"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	About     *string `json:"about"`
	Title     *string `json:"title"`
}

type PlayerSummary struct {
	Username string `json:"username"`
	Result   int    `json:"result"`
}

type Sport struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type StatsEntry struct {
	Wins   int `json:"wins"`
	Ties   int `json:"ties"`
	Losses int `json:"losses"`
}

type StatsForPlayer struct {
	User  *User       `json:"user"`
	Stats *StatsEntry `json:"stats"`
}

type StatsForSport struct {
	SportName string            `json:"sportName"`
	Stats     []*StatsForPlayer `json:"stats"`
}

type StatsSummary struct {
	Stats []*StatsForSport `json:"stats"`
}

type TagAvailable struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
}

type User struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Avatar    *string `json:"avatar"`
	Email     string  `json:"email"`
	About     *string `json:"about"`
	Title     *string `json:"title"`
}
